console.log("Jesus is the king!")
console.log('耶穌是王!')
console.log("Jesus es el rey!")
console.log('يسوع هو الملك!')
console.log('イエスこそが王なのです！')
console.log("Иисус – царь!")
console.log('ישו הוא המלך!')
console.log('#####################')
console.log("Made by Mag1")